include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
      - "**/*.g.dart"
      - "**/*.freezed.dart"
      - "**/*.mocks.dart"
      - "**/*.config.dart"

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - prefer_single_quotes
    - avoid_returning_null
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - no_duplicate_case_values
    - no_default_cases
    - avoid_slow_async_io
    - prefer_void_to_null
    - sort_constructors_first
#    - always_use_package_imports
#    - close_sinks
#    - comment_references
#    - one_member_abstracts
#    - only_throw_errors
#    - package_api_docs
#    - prefer_final_in_for_each
