name: loginio
description: A new Flutter project.


version: 1.0.0+2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^4.0.1
  bloc: ^8.0.2

  flutter_svg: ^1.0.3

  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  google_maps_cluster_manager: ^3.0.0+1
  modal_bottom_sheet: ^2.0.1

  equatable: ^2.0.3

  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  flutter_screenutil: ^5.3.1
  flutter_bloc: ^8.0.1
  flutter_polyline_points: ^1.0.0

  google_maps_flutter: ^2.1.2
  bloc_concurrency: ^0.2.0

  hive_flutter: ^1.1.0 #todo add caching
  json_annotation: ^4.4.0
  freezed_annotation: ^2.0.3

  location: ^4.3.0

  permission_handler: ^9.2.0
  retrofit: ^3.0.1+1

  sliding_up_panel: ^2.0.0+1

  flutter_native_splash: ^2.1.6
  google_fonts: ^2.2.0
  get_it: ^7.2.0
  rxdart: ^0.27.3
  injectable: ^1.5.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.1
  auto_route_generator: ^4.0.0
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  freezed: ^2.0.3+1
  environment_config: ^3.0.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/svg/
    - assets/map_pins/
    - assets/map_markers/
#    - assets/langs/
#    - assets/flr/

